import time
from pynput.keyboard import Key, Controller

keyboard = Controller()
my_time = time.strftime("%H:%M:%S", time.localtime())
print("Start: "+ my_time)
time.sleep(2)
my_time = time.strftime("%H:%M:%S", time.localtime())
while 1:
    for i in range(7):
        keyboard.press('f')
        time.sleep(2)
        keyboard.release('f')
        time.sleep(2)
        if i < 6:
            keyboard.press('1')
            keyboard.press(Key.tab)
            time.sleep(0.2)
            keyboard.release(Key.tab)
            keyboard.release('1')
            time.sleep(1)
            keyboard.press(Key.down)
            time.sleep(0.1)
            keyboard.release(Key.down)
            time.sleep(0.5)
            keyboard.press('g')
            time.sleep(0.1)
            keyboard.release('g')
            time.sleep(1)
            keyboard.press('g')
            time.sleep(0.1)
            keyboard.release('g')
            time.sleep(11)

    time.sleep(4)
    keyboard.press(Key.f1)
    time.sleep(0.2)
    keyboard.release(Key.f1)
    time.sleep(1)
    keyboard.press('f')
    time.sleep(0.2)
    keyboard.release('f')
    time.sleep(1.0)
    keyboard.press(Key.up)
    time.sleep(0.1)
    keyboard.release(Key.up)
    time.sleep(0.5)
    keyboard.press(Key.up)
    time.sleep(0.1)
    keyboard.release(Key.up)
    time.sleep(0.5)
    keyboard.press('g')
    time.sleep(0.1)
    keyboard.release('g')
    time.sleep(1.0)
    keyboard.press('g')
    time.sleep(0.1)
    keyboard.release('g')
    time.sleep(8)
    keyboard.press('g')
    time.sleep(0.1)
    keyboard.release('g')
    time.sleep(22.0)
    keyboard.press('t')
    time.sleep(0.1)
    keyboard.release('t')
    time.sleep(2)
my_time = time.strftime("%H:%M:%S", time.localtime())
print("End: "+ my_time)